### ISSUE TITLE
Ability to detect of fan fully off or just off due to lack of movement

### ISSUE THREAD

**Issue by jyavenard** [mikelawrence/senseme-hacs#14]
This isn't a bug or issue per say; so I apologise in advance but I didn't know of a better way to ask those questions.

The fan (either the fan itself or its light) can be made to turn off after a given time and it will restart automatically if it detects motion sensing.

I'd like to know if it's possible to differentiate between the two modes: e.g. the light is off because off was sent as a wifi-command or the remote; or because it just automatically turned-off and may go back on.
If it's been manually turned off, it won't turn back on automatically.

The reason for this I have installed a zigbee switch, it has a light depending if it's off (blue) or on (red).

I made a rule in HA that mirror the state of the fan with the switch and vice-versa; so that a press of the button on the switch, will turn on or off the fan or its light.
Fan and switch aren't electrically connected.

So if I turn the fan off, the switch's light to reflect that and show a blue light, and red when on.

However, I'd like the light to stay red to indicate that the fan is still powered and motion sensing will turn it back on.
Only if I press the switch, will the fan fully go off.

To achieve this, I need to be able to distinguish between an auto-off and a full off.
Is there a way to listen to that state change?

thanks !

PS: here is my current HA rule:
```
- alias: Sync Master Top - Fan Light
  trigger:
    - entity_id: switch.master_switch_1, light.master_bedroom_fan_light
      platform: state
  condition:
    - condition: template
       value_template: "{{ 'on' in trigger.to_state.state or 'off' in trigger.to_state.state }}"
    - condition: template
       value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
  action:
    - service_template: homeassistant.turn_{{trigger.to_state.state}}
      # We only want to send off to the device that didn't cause the trigger; so that the sensing auto-off works.
      # So only if we explicitly turn off the wall switch will we turn off the fan.
      data_template:
         entity_id: "{{ 'light.master_bedroom_fan_light' if trigger.to_state.object_id[-1:] == '1' else 'switch.master_switch_1' }}"
    - delay: 1
  mode: single
```
