### ISSUE TITLE
Add support for Sleep Mode

### ISSUE THREAD

**Issue by DaveO16176** [mikelawrence/senseme-hacs#18]
Would it be possible to add support for sleep mode so it can be selected via Home Assistant and not just by the fan's remote or the app?

**Comment by claytonjn** [comment]
Built-in support would be nice. Until then you can just configure a `command_line` switch manually:

```yaml
platform: command_line
  switches:
    master_bedroom_fan_sleep_mode:
      command_off: >
        echo "<00:11:22:33:44:55;SLEEP;STATE;OFF>" | nc -w1 -u fan.ip.or.dns 31415
      command_on: >
        echo "<00:11:22:33:44:55;SLEEP;STATE;ON>" | nc -w1 -u fan.ip.or.dns 31415
```

You just have to replace `00:11:22:33:44:55` with the mac address of the fan and `fan.ip.or.dns` with the IP address or a DNS address of the fan.

**Comment by mikelawrence** [comment]
That's a handy way to handle the Sleep Mode in HA. Both of my fans are down right now so I don't have any way to test this, have you tested the switch? The reason I ask is sometimes SenseME commands require a ";SET"

Either way I wouldn't mind adding Sleep Mode Switch to the component once I get fans working again.

**Comment by claytonjn** [comment]
Yes, I've had that configured since long before you released the senseme component. It's at least working on my "H series" fan.

**Comment by DaveO16176** [comment]
Thanks so much for the solution!  I had to change it a bit to get it working.  This worked for me:

```
switch:    
  - platform: command_line
    switches:
      master_bedroom_fan_sleep_mode:
        command_off: >
          echo "<00:11:22:33:44:55;SLEEP;STATE;OFF>" | nc -w1 -u fan.ip.or.dns 31415
        command_on: >
          echo "<200:11:22:33:44:55;SLEEP;STATE;ON>" | nc -w1 -u fan.ip.or.dns 31415
```
